require_relative '../playlist_builder'

class SystemPlaylistConcreteBuilder < PlaylistBuilder
  attr_accessor :system_playlist

  def initialize
    reset
  end

  def reset
    @system_playlist = Playlist.new
  end

  def playlist
    system_playlist = @system_playlist
    reset
    system_playlist
  end

  def set_id(id)
    @system_playlist.set_id(id)
  end

  def set_metadata(name, creator, description)
    @system_playlist.set_name('system')
    @system_playlist.set_creator('system')
    @system_playlist.set_description(description)
    @system_playlist.set_creation_date
  end

  def set_system_settings(privacy_settings)
    @system_playlist.set_privacy_settings(privacy_settings)
    @system_playlist.set_allowed_order(%w[regular mixed smart custom])
    @system_playlist.set_type('autogenerated-playlist')
    @system_playlist.set_dynamic(true)
    @system_playlist.set_persistent(false)
  end

  def set_tracks(tracks)
    @system_playlist.set_tracks(tracks)
  end
end